repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: check-json
    -   id: flake8
        args: ["--count", "--ignore=E501,F401", --exclude=.venv", "--statistics"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy

-   repo: git://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
    -   id: rst-linter

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: markdownlint

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
